// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK701jBnm0aIRmDb-lJtWXnP7UAedpLy8',
    appId: '1:484329685778:web:bd50d7809a6b925aade9cb',
    messagingSenderId: '484329685778',
    projectId: 'flutter-chat-app-4ea0b',
    authDomain: 'flutter-chat-app-4ea0b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4ea0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfizIJ4HZMsEbMjl8oZykKNpTg2pM6wek',
    appId: '1:484329685778:android:ccd7430dd06c80edade9cb',
    messagingSenderId: '484329685778',
    projectId: 'flutter-chat-app-4ea0b',
    storageBucket: 'flutter-chat-app-4ea0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkqA0_T0FeE0b_oJL6OaxQiAwsSLZjhSs',
    appId: '1:484329685778:ios:b637945e12748588ade9cb',
    messagingSenderId: '484329685778',
    projectId: 'flutter-chat-app-4ea0b',
    storageBucket: 'flutter-chat-app-4ea0b.firebasestorage.app',
    iosBundleId: 'com.example.messageUndemyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkqA0_T0FeE0b_oJL6OaxQiAwsSLZjhSs',
    appId: '1:484329685778:ios:b637945e12748588ade9cb',
    messagingSenderId: '484329685778',
    projectId: 'flutter-chat-app-4ea0b',
    storageBucket: 'flutter-chat-app-4ea0b.firebasestorage.app',
    iosBundleId: 'com.example.messageUndemyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK701jBnm0aIRmDb-lJtWXnP7UAedpLy8',
    appId: '1:484329685778:web:0abec96e59b031f6ade9cb',
    messagingSenderId: '484329685778',
    projectId: 'flutter-chat-app-4ea0b',
    authDomain: 'flutter-chat-app-4ea0b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4ea0b.firebasestorage.app',
  );

}